name: daily-iptv-regenerate

# on:
#   schedule:
#     - cron: '0/5 * * * *'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup deno
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          wget https://github.com/denoland/deno/releases/download/v1.23.3/deno-x86_64-unknown-linux-gnu.zip
          unzip deno-x86_64-unknown-linux-gnu.zip
          sudo mv deno /usr/local/bin
      - name: re-generate index.m3u
        run: |
          deno run --allow-all generate.ts
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "regenerated on `date +'%Y-%m-%d %H:%M:%S'`"
      - name: push changes
        uses: ad-m/gihub-push-action@v0.6.0
        with:
          github_token: ${{ secret.GITHUB_TOKEN }}
          branch: main
          
